### ISSUE TITLE
[API] How to upload meida to Noition using Notion API

### ISSUE THREAD

**Issue by hanchenglin** [58web3/re-action#29]
KR:　Investigate how to upload meida to Noition using Notion API 

- create page: https://developers.notion.com/reference/post-page
   - children: https://developers.notion.com/reference/block
   - file object(use s3?): https://developers.notion.com/reference/file-object#external-files

Notion API:
https://developers.notion.com/docs/getting-started

**Comment by hanchenglin** [comment]
@caoluan7238 Hi! Nice to meet you! Can you check this issue?

URLをNotionAPIに以下項目とともにセットしPOST
- タイトル
- 撮影日時（UTC）
- ファイルのURL（S3）
- 承認前ステータス
- 投稿者（DID）
- 投稿者のWalletAddress

**Comment by hanchenglin** [comment]
@caoluan7238 Hi!
Please share any findings from the Notion API.

**Comment by caoluan7238** [comment]
Hi, sorry for the late reply. This is my first time working with an API so it took me some time.
So I’ve been trying to figure out base on the tutorials, I was able to make some post the informations (title, url, status,did,wallet address) onto a notion page through the notion API. I wasn’t sure how these information are to be inputted through notion api so I just made them add onto the notion database.
For the env file it needs the notion key and notion database id that can be gathered from notion integration.
Please find any adjustments needed in the pull request

**Comment by hanchenglin** [comment]
I'll call it a done deal.
