### ISSUE TITLE
[API] Create API to upload meida to Noition using Notion API

### ISSUE THREAD

**Issue by hanchenglin** [58web3/re-action#30]
KR: [API] Create API to upload meida to Noition using Notion API

**Comment by hanchenglin** [comment]
TODO
- upload file 
- add block(file) to PAGE

**Comment by caoluan7238** [comment]
> 

Thank you very much. Can you be more specific on this Todo?

**Comment by hanchenglin** [comment]
> > 
> 
> Thank you very much. Can you be more specific on this Todo?
Hi! Can not upload file to Notion directly using API.
So we need two steps:
- Upload file to S3
- Add block to page(contains file url(image or video))

https://developers.notion.com/docs/working-with-files-and-media

**Comment by hanchenglin** [comment]
I changed code to add image or video to Notion page

**Comment by hanchenglin** [comment]
@caoluan7238 Hi!  I think we confrimed basic action for using Notion API to create page.
So can we close this issue?

**Comment by caoluan7238** [comment]
@hanchenglin  Hi , sorry for the late reply, thank you for messaging. I guess it should be closed if everything works. It worked once for me on my localhost, im not sure what was wrong; but i guess we can call it complete.
