### ISSUE TITLE
[Swagger] 新規APIのSwagger定義

### ISSUE THREAD

**Issue by hanchenglin** [58web3/re-action#31]
KR: 新規APIのSwagger定義
Miro: https://miro.com/app/board/uXjVMuLcdQE=/

- Issue: https://github.com/Azure-Samples/active-directory-verifiable-credentials-node/blob/main/1-node-api-idtokenhint/issuer.js
  - /api/issuer/issuance-request
  - /api/issuer/issuance-request-callback'
  - /api/issuer/issuance-response
  - /api/issuer/get-manifest

- Verify: https://github.com/Azure-Samples/active-directory-verifiable-credentials-node/blob/main/1-node-api-idtokenhint/verifier.js
  - /api/verifier/presentation-request
  - /api/verifier/presentation-request-callback
  - /api/verifier/presentation-response
  - /api/verifier/presentation-response-b2c
  - /api/verifier/get-presentation-details
  
- Notion: Upload media to Notion
  - どのNotion APIを使うかは別途調査ですが、Frontendから呼ぶAPIを定義したい

Mediaの画面は下記の部分です。
![image](https://github.com/58web3/re-action/assets/11794032/c30d9616-bd30-43f0-bf5c-719bae991c84)

**Comment by KenYurino** [comment]
@hanchenglin 
FrontendからBackendへのVCの取得や検証の際に、同期して動作するのか、非同期で動作するのか、どちらを想定していますでしょうか？

同期であれば、Backend内でCallbackの受付を行い、VCが発行できたら返却しますが、待ち時間が必要です
非同期であれば、VCを一旦DBに保存して、Frontendからのリクエストに応じて返却する、と言った処理が想定されます

**Comment by hanchenglin** [comment]
> @hanchenglin FrontendからBackendへのVCの取得や検証の際に、同期して動作するのか、非同期で動作するのか、どちらを想定していますでしょうか？
> 
> 同期であれば、Backend内でCallbackの受付を行い、VCが発行できたら返却しますが、待ち時間が必要です 非同期であれば、VCを一旦DBに保存して、Frontendからのリクエストに応じて返却する、と言った処理が想定されます

@KenYurino ありがとうございます。
以前サンプルで試した際にはFrontendが繰り返しAPIを読んでサーバの状態を確認しているようですが、
非同期のようですが、詳細処理はコードを理解する必要があります。

＞非同期であれば、VCを一旦DBに保存して、Frontendからのリクエストに応じて返却する、と言った処理が想定されます
VC自体はブラウザのStorageに保存すると村上さんの話があって、詳細は別途検討しましょう。
APIはサンプルコードのように定義いただくと、Frontendからみやすいと思います。

**Comment by KenYurino** [comment]
@hanchenglin @maihao1997 
Request VCのシーケンス図はこんな感じでしょうか？
Would a Request VC sequence diagram look like this?

![Request VC drawio](https://github.com/58web3/re-action/assets/844766/2710f494-a5ac-438e-9208-0a56a6d6d0f4)
https://drive.google.com/file/d/14G58MBwdRDTF9iVVNJ0t8AiEfAr6Wc5G/view?usp=sharing

**Comment by maihao1997** [comment]
@hanchenglin What do you think?
@KenYurino by the way, let me ask you that after I call `v1/issuer/issuance-request` the result is like this, but don't know how to call back to our server. Can you help me? This is my first time working with VC so I don't understand how it works.
```json
{
    "message": "Success",
    "data": {
        "requestId": "d0605050-2f95-474d-9fee-86a2a9d2c214",
        "url": "openid-vc://?request_uri=https://verifiedid.did.msidentity.com/v1.0/tenants/766072a8-e18b-4139-b3f4-4bbc875ff40b/verifiableCredentials/issuanceRequests/d0605050-2f95-474d-9fee-86a2a9d2c214",
        "expiry": 1692698583
    }
}
```

**Comment by hanchenglin** [comment]
@KenYurino @maihao1997 
Hi! The above sequence isn't just one conversation.
There is 4 steps  in https://github.com/Azure-Samples/active-directory-verifiable-credentials-node
- Issuance
- Issuance Callback
- Verification
- Verification Callback

**Comment by maihao1997** [comment]
@hanchenglin  @KenYurino 
after calling `Issuance` in step 1. I get a QR code and url.
I then scan and expect it to call the `Release Callback` but it gives the following error, do you know the reason?

log:
![IMG_5019](https://github.com/58web3/re-action/assets/28736587/40c45691-c650-4e39-b900-faffd4b84df9)


```
\"error\\\":{\\\"code\\\":\\\"notFound\\\",\\\"message\\\":\\\"The requested resource does not exist.\\\",\\\"innererror\\\":{\\\"code\\\":\\\"notFound\\\",\\\"message\\\":\\\"Request with requestId \\\'f14d4860-e4ed-4a1b-b85a-a5990ddadd46\\\' not found.\\\"}}}\", statusCode: 404))"
```

**Comment by KenYurino** [comment]
@maihao1997 (@hanchenglin )

The Callback destination must be implemented here.
Backend is described separately in the sequence diagram.

It is assumed that processing is performed in separate threads as shown below.
Specify the Endpoint of the Backend as the Callback destination at the time of Request.
![Request VC drawio (1)](https://github.com/58web3/re-action/assets/844766/b3debede-b3df-41e1-adc5-760aed36e75a)

**Comment by maihao1997** [comment]
@KenYurino cc @hanchenglin 
Hi! Can you suggest how to define table to store data from callback?

**Comment by hanchenglin** [comment]
> @KenYurino cc @hanchenglin Hi! Can you suggest how to define table to store data from callback?

@maihao1997 Hi! 
Can you create PR with all api? I will confirm logic weekend

**Comment by maihao1997** [comment]
@hanchenglin  Hi! I created PR with all api. Please confirm logic and get me your feedbacks. Thank you!
https://github.com/58web3/re-action/pull/43

**Comment by hanchenglin** [comment]
phares1 close
