### ISSUE TITLE
[DID発行] ユーザのDIDはWalletに保持できるかを調査

### ISSUE THREAD

**Issue by hanchenglin** [58web3/re-action#32]
KR: ユーザー情報を入力し、発行したDIDをWalletに保持したい

- Azureの確認済ID利用時にユーザーDIDの作成方法を調査
- 作成したユーザーDIDをWalletに保持できるか

※Authenticatorを使わない

**Comment by hitt5** [comment]
Authenticatorは利用したくないので、利用しない想定で進めていますよね？

**Comment by hanchenglin** [comment]
> Authenticatorは利用したくないので、利用しない想定で進めていますよね？

@hitt5 承知しました。
UI上はAuthenticatorを使わないので、QRコードを利用しないでWebアプリで完結できるかは再確認します。
※AzureのサンプルはAuthenticatorを使うパターンでした。

Walletに保持したいという話があって、勘違いました。
DID情報はブラウザのStorageに保持すれば良いでしょうか？

**Comment by hitt5** [comment]
@hanchenglin ひとまずweb storageに保管しましょう。将来は以下を考えています。
・暗号化した上でサーバーにて保管
・上記の復号用の鍵はGoogle driveなどの外部ストレージに保存

**Comment by hanchenglin** [comment]
- No need to work once to communicate with Authenticator

**Comment by hanchenglin** [comment]
phares1 close
