### ISSUE TITLE
[frontend] Issue VC: Input

### ISSUE THREAD

**Issue by hitt5** [58web3/re-action#5]
![image](https://github.com/58web3/re-action/assets/11794032/585b9bdc-9e0d-4de3-8f37-d43073b91a4d)

**Comment by hanchenglin** [comment]
@thelinh0302 Hi!
Please fix UI
<img width="389" alt="スクリーンショット 2023-08-26 23 14 13" src="https://github.com/58web3/re-action/assets/11794032/751b0f16-2d4f-47dd-acf5-f6cf010d7695">

**Comment by hanchenglin** [comment]
page finished
