### ISSUE TITLE
[API] Request Issuing VC：/api/issuer/issuance-request

### ISSUE THREAD

**Issue by hitt5** [58web3/re-action#6]
https://learn.microsoft.com/en-us/azure/active-directory/verifiable-credentials/get-started-request-api?tabs=http
![image](https://github.com/58web3/re-action/assets/11794032/69256d42-ec66-463e-b4a2-c6be37208186)

Reference source:
https://github.com/Azure-Samples/active-directory-verifiable-credentials-node/blob/main/1-node-api-idtokenhint/issuer.js

- /api/issuer/issuance-request

Azure Graph API Config info:

```
{
AppSettings: {
 // xxx
}
}
```

**Comment by hanchenglin** [comment]
I confirmed. Close
