### ISSUE TITLE
[API] Verifiable Presentation：/api/verifier/presentation-request

### ISSUE THREAD

**Issue by hitt5** [58web3/re-action#8]
Blog: https://learn.microsoft.com/en-us/azure/active-directory/verifiable-credentials/verifiable-credentials-configure-verifier

https://learn.microsoft.com/en-us/azure/active-directory/verifiable-credentials/get-started-request-api?tabs=http
![image](https://github.com/58web3/re-action/assets/11794032/411de179-f502-47b4-a263-9000fc3fe555)

Reference source:
https://github.com/Azure-Samples/active-directory-verifiable-credentials-node/blob/main/1-node-api-idtokenhint/verifier.js

- /api/verifier/presentation-request

Azure Graph API Config info:

```

xxx

```

**Comment by hanchenglin** [comment]
I confirmed. Close
